-- This module is the root of the KaplanskyIdempotentConjectureCanonicalLaneLean Lean proof package.
import KaplanskyIdempotentConjectureCanonicalLaneLean.Basic
import KaplanskyIdempotentConjectureCanonicalLaneLean.SourcePackage
import KaplanskyIdempotentConjectureCanonicalLaneLean.SourceDependencies
import KaplanskyIdempotentConjectureCanonicalLaneLean.Formalization
import KaplanskyIdempotentConjectureCanonicalLaneLean.ReviewerBridge
import KaplanskyIdempotentConjectureCanonicalLaneLean.TheoremStatement
