-- This module is the root of the KaplanskyIdempotentConjectureCanonicalLaneLean Lean proof package.
import KaplanskyIdempotentConjectureCanonicalLaneLean.Basic
import KaplanskyIdempotentConjectureCanonicalLaneLean.SourcePackage
import KaplanskyIdempotentConjectureCanonicalLaneLean.SourceDependencies
import KaplanskyIdempotentConjectureCanonicalLaneLean.Formalization
import KaplanskyIdempotentConjectureCanonicalLaneLean.ReviewerBridge
import KaplanskyIdempotentConjectureCanonicalLaneLean.TheoremStatement
import KaplanskyIdempotentConjectureCanonicalLaneLean.MathlibObjects
import KaplanskyIdempotentConjectureCanonicalLaneLean.AdmissibleClass
import KaplanskyIdempotentConjectureCanonicalLaneLean.Projection
import KaplanskyIdempotentConjectureCanonicalLaneLean.BridgeLemmas
import KaplanskyIdempotentConjectureCanonicalLaneLean.GateLemmas
import KaplanskyIdempotentConjectureCanonicalLaneLean.FinalTheorem
import KaplanskyIdempotentConjectureCanonicalLaneLean.MathlibStatement
